// Seeds FAKE demo tenants and users for development/staging testing.
// Refuses to run when LUNA_ENV=production.
//
//   node --env-file=.env.local scripts/seed-demo.js --confirm <projectId>
//
// Idempotent: re-running keeps existing businesses, re-applies memberships,
// and issues NEW random passwords for every demo user. Credentials are
// written to .demo-credentials.local.md (gitignored) — never committed,
// never printed.

import { randomBytes } from "node:crypto";
import { writeFileSync } from "node:fs";
import { parseArgs, connect } from "./_cli.js";
import { seedPlans, createBusiness, ensureAuthUser, addMember, assignPlan, ProvisioningError } from "../netlify/functions/_lib/provisioning.js";

const DEMO_DOMAIN = "luna.test"; // reserved TLD — can never be a real mailbox

const BUSINESSES = [
  { id: "demo-distributor-a", name: "Demo Distributor A", plan: "growth", status: "active" },
  { id: "demo-distributor-b", name: "Demo Distributor B", plan: "starter", status: "active" },
  { id: "demo-retailer-c", name: "Demo Retailer C", plan: "starter", status: "suspended" },
];

// Order matters: owners first (they become each user's default business).
const MEMBERS = [
  { key: "owner.a", name: "Owner A (Demo)", business: "demo-distributor-a", role: "owner", owner: true },
  { key: "manager.a", name: "Manager A (Demo)", business: "demo-distributor-a", role: "manager" },
  { key: "staff.a", name: "Staff A (Demo)", business: "demo-distributor-a", role: "staff" },
  { key: "disabled.a", name: "Disabled Staff A (Demo)", business: "demo-distributor-a", role: "staff", status: "disabled" },
  { key: "owner.b", name: "Owner B (Demo)", business: "demo-distributor-b", role: "owner", owner: true },
  { key: "multi", name: "Multi-Business User (Demo)", business: "demo-distributor-a", role: "staff" },
  { key: "multi", name: "Multi-Business User (Demo)", business: "demo-distributor-b", role: "manager" },
  { key: "owner.c", name: "Owner C (Demo)", business: "demo-retailer-c", role: "owner", owner: true },
  { key: "staff.c", name: "Staff C (Demo)", business: "demo-retailer-c", role: "staff" },
];

const NOTES = {
  "owner.a": "Owner of A (Growth). Sees every module incl. Users & Settings.",
  "manager.a": "Manager/Admin of A. No subscription or team management.",
  "staff.a": "Staff of A. Orders/Payments/Inventory/Customers only.",
  "disabled.a": "Membership in A is DISABLED → must be refused.",
  "owner.b": "Owner of B (Starter).",
  multi: "Staff in A (default) AND Manager in B → business switcher.",
  "owner.c": "Owner of C — subscription SUSPENDED → read-only banner.",
  "staff.c": "Staff of C — suspended business, read-only.",
};

const password = () => `Demo-${randomBytes(9).toString("base64url")}`;

const args = parseArgs();
const { db, admin, auth } = await connect(args, { forbidProduction: true });

console.log("Plans:");
for (const r of await seedPlans({ db, admin })) console.log(`  ${r.id}: ${r.action}`);

console.log("Businesses:");
for (const b of BUSINESSES) {
  try {
    await createBusiness({ db, admin, name: b.name, planId: b.plan, subscriptionStatus: b.status, businessId: b.id, isDemo: true, createdBy: "seed-demo" });
    console.log(`  ${b.id}: created (${b.plan}, ${b.status})`);
  } catch (err) {
    if (!(err instanceof ProvisioningError && err.code === "business-exists")) throw err;
    await db.collection("businesses").doc(b.id).update({ "subscription.status": b.status });
    await assignPlan({ db, admin, businessId: b.id, planId: b.plan, actor: "seed-demo", reason: "seed-demo re-apply" });
    console.log(`  ${b.id}: exists — status/plan/entitlements re-applied`);
  }
}

console.log("Users & memberships:");
const credentials = new Map();
for (const m of MEMBERS) {
  const email = `${m.key}@${DEMO_DOMAIN}`;
  if (!credentials.has(m.key)) {
    const user = await ensureAuthUser({ auth, email, name: m.name });
    const pw = password();
    await auth.updateUser(user.uid, { password: pw, displayName: m.name, disabled: false });
    credentials.set(m.key, { uid: user.uid, email, password: pw });
  }
  const { uid } = credentials.get(m.key);
  await addMember({
    db,
    admin,
    businessId: m.business,
    uid,
    email,
    name: m.name,
    roleTemplate: m.role,
    isAccountOwner: Boolean(m.owner),
    status: m.status || "active",
    createdBy: "seed-demo",
  });
  console.log(`  ${email} → ${m.business} as ${m.role}${m.status === "disabled" ? " (DISABLED)" : ""}`);
}

const lines = [
  `# Luna demo credentials — ${process.env.FIREBASE_PROJECT_ID} (${process.env.LUNA_ENV})`,
  "",
  "Generated by scripts/seed-demo.js. FAKE accounts for testing only. Gitignored — do not commit or share.",
  "Re-running the seed issues new passwords.",
  "",
  "| Email | Password | Notes |",
  "|---|---|---|",
  ...[...credentials.entries()].map(([key, c]) => `| ${c.email} | \`${c.password}\` | ${NOTES[key] || ""} |`),
  "",
  "Business ids: " + BUSINESSES.map((b) => `\`${b.id}\``).join(", "),
  "",
];
writeFileSync(new URL("../.demo-credentials.local.md", import.meta.url), lines.join("\n"));
console.log("\n✔ Demo credentials written to .demo-credentials.local.md (gitignored).");
